### ISSUE TITLE
Unable to use library on iOS with use_frameworks! directive

### ISSUE THREAD

**Issue by octavezero** [prscX/react-native-selection-menu#12]
Hi,

I am trying to use the v1 of the library on RN 0.60 on iOS.

The specified instructions are causing an issue with some other dependencies on the project. Specifically this line in the Podfile - 

```
use_frameworks!
```

Placing this line in the podfile is causing the pod update to crash with the following error -

```
The (Project) target has transitive dependencies that include statically linked binaries: (project/ios/Pods/Crashlytics/iOS/Crashlytics.framework)
```

If I remove the use_frameworks! directive to solve the above issue, the project build for iOS fails due to the following issue - 

```
project/node_modules/react-native-selection-menu/ios/RNSelectionMenu.h:4:9: fatal error: 'RSSelectionMenu/RSSelectionMenu-Swift.h' file not found
#import "RSSelectionMenu/RSSelectionMenu-Swift.h"
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Would be very appreciated if I could get some help with this.

**Comment by prscX** [comment]
Thanks @quantumkv for raising the issue.

While porting I have tested it with RN61. I believe, as per [RN Release Notes](https://github.com/facebook/react-native/releases/tag/v0.61.0), they have provided better support for CocoaPods with `use_frameworks!` in RN61.

Looks like similar issue. Could you please try it with RN61 once and share your findings.

Thanks
</ Pranav >

**Comment by co2nut** [comment]
![image](https://user-images.githubusercontent.com/4594000/70117344-3059ee80-16a0-11ea-81df-b74e4dd859bd.png)
The build was successful, but I'm facing issue as screenshot above with RN61

**Comment by octavezero** [comment]
Sorry for replying late. It is working with RN 0.61.5.
